version: "3.9"

services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    restart: "unless-stopped"
    networks:
      - backend

  server:
    container_name: api_server_container
    build:
      context: ./
      dockerfile: Dockerfile.prod
    ports:
      - "3000:5000"
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
  redis:
    image: redis:alpine3.20
    restart: 'unless-stopped'
    networks:
      - backend


networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
