services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.5g'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - ./public:/var/www/zameen
    restart: always
    networks:
      - backend

  server:
    container_name: api_server_container
    build:
      context: ./
      dockerfile: Dockerfile.prod
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: '1.6g'
    ports:
      - "3000:5000"
    volumes:
      - ./:/app
      - /app/node_modules
    restart: always
    networks:
      - backend
  redis:
    image: redis:alpine3.20
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.5g'
    networks:
      - backend


networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
