name: Run Migrations

on:
  push:
    # paths:
    #   - 'src/migrations/**'
    # branches:
    #   - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run Sequelize migrations
        env:
          EC2_ENV_FILE: ${{ secrets.CODE_ENV_FILE }}
          NODE_ENV: production
        run: |
          npx sequelize-cli db:migrate --debug
