name: Run tests

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run unit tests
        env:
          TEST_ENV_FILE: ${{ secrets.TEST_ENV_FILE }}
        run: |
          echo "$TEST_ENV_FILE" > .env.test.local
          pnpm test
